package com.rnridablegpstracker

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.ReadableMap

/**
 * This is a temporary base class for the TurboModule.
 * In a proper New Architecture setup, this would be auto-generated by Codegen.
 * 
 * TODO: Replace with proper Codegen setup when available
 */
abstract class NativeRidableGpsTrackerSpec(reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext) {

    @ReactMethod
    abstract fun configure(config: ReadableMap, promise: Promise)

    @ReactMethod
    abstract fun start(promise: Promise)

    @ReactMethod
    abstract fun stop(promise: Promise)

    @ReactMethod
    abstract fun getCurrentLocation(promise: Promise)

    @ReactMethod
    abstract fun checkStatus(promise: Promise)

    @ReactMethod
    abstract fun requestPermissions(promise: Promise)

    @ReactMethod
    abstract fun openLocationSettings()

    @ReactMethod
    abstract fun addListener(eventName: String)

    @ReactMethod
    abstract fun removeListeners(count: Double)
}
