platform :ios, '13.0'

target 'GPSTrackerExample' do
  use_frameworks!
  
  # Note: This is a pure native iOS example app
  # It doesn't use React Native or the RNRidableGpsTracker module
  # It uses CoreLocation directly for GPS tracking demonstration
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
